#!/usr/bin/env python3
"""
Test Agent Document Generation
"""

import os
import sys
import pytest
from pathlib import Path

# Add src to path
sys.path.append(os.path.join(os.path.dirname(__file__), 'src'))

@pytest.mark.asyncio
async def test_agent_document_generation():
    """Test document generation through the agent"""
    print("🧪 Testing Agent Document Generation")
    print("=" * 50)
    
    try:
        from aws_devops_agent.main import AWSDevOpsAgentV2
        
        # Initialize agent
        agent = AWSDevOpsAgentV2(interactive_account_selection=False)
        
        # Test 1: Simple document generation request
        print("\n1️⃣ Testing simple document generation...")
        response = await agent.chat("Generate a simple test document with title 'Test Document' and content 'This is a test document generated by the agent'")
        print("Response:", response[:200] + "..." if len(response) > 200 else response)
        
        # Test 2: Check if documents were created
        print("\n2️⃣ Checking generated documents...")
        reports_dir = Path("reports")
        if reports_dir.exists():
            total_files = 0
            for subdir in reports_dir.iterdir():
                if subdir.is_dir():
                    files = list(subdir.glob("*"))
                    total_files += len(files)
                    print(f"   📁 {subdir.name}: {len(files)} files")
            
            print(f"   📊 Total files: {total_files}")
        else:
            print("   ❌ Reports directory not found")
        
        # Test 3: List documents through agent
        print("\n3️⃣ Testing document listing through agent...")
        response = await agent.chat("List all generated documents")
        print("Response:", response[:200] + "..." if len(response) > 200 else response)
        
        print("\n🎉 Agent document generation test completed!")
        
    except Exception as e:
        print(f"❌ Test failed with error: {str(e)}")
        import traceback
        traceback.print_exc()


if __name__ == "__main__":
    import asyncio
    asyncio.run(test_agent_document_generation())
